### ISSUE TITLE
Not compatible with SpongeForge, mixin version too old

### ISSUE THREAD

**Issue by DMahalko** [Ordinastie/MalisisCore#151]
Can you please update the mixin version you are using, so that this mod will work properly with SpongeForge?

Discussed in an issue that I posted to the SpongeForge dev team:
https://github.com/SpongePowered/SpongeForge/issues/2254

**Comment by wormzjl** [comment]
+1 to this

**Comment by bloodmc** [comment]
Do the following until dev can update

* Open malisiscore jar and edit mixins.malisiscore.core.json. Change 0.7.4 to 0.7.10
* Delete the org folder

Everything should work normally.

**Comment by DMahalko** [comment]
bloodmc, I don't normally work with editing jars, but I tried your suggestion and it didn't work for me.

unzip the malisiscore jar, rename it to *.disabled
delete the org directory from the extracted jar directory
start FML with extracted malisiscore mod directory in /mods
apparently forgemodloader hates extracted jars, so force-quits itself
zip -r the extracted malisiscore back into a zip, remove the extracted dir

start FML....

`[15:46:32] [Server thread/TRACE] [FML]: Sending event FMLConstructionEvent to mod malisiscore
[15:46:32] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderException: malisiscore Failed load class: net.malisis.core.MalisisCore

        at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:533) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.ClassNotFoundException: net.malisis.core.MalisisCore
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
        at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75) ~[ModClassLoader.class:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_144]
        at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:528) ~[FMLModContainer.class:?]
        ... 31 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
        at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75) ~[ModClassLoader.class:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_144]
        at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:528) ~[FMLModContainer.class:?]
        ... 31 more
`

If you have more detailed instructions I will try them.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2254#issuecomment-399810578
> MalisisCore is shipping an older version of Mixin. You can get around this by renaming the SpongeForge JAR to something like `aaaaSpongeForge....`.

**Comment by bloodmc** [comment]
@DMahalko Forgot to mention
```
Open malisiscore jar and edit mixins.malisiscore.core.json. Change 0.7.4 to 0.7.10
```

You can also do what kashike mentioned.

**Comment by MarkTwoFive** [comment]
One of the effects which made me submit #147

**Comment by rouing** [comment]
+1

**Comment by Dockter** [comment]
Use this: https://ore.spongepowered.org/Dockter/MalisisCore

**Comment by sfxworks** [comment]
```
[22:18:43] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/world/chunk/BlockStateContainer
        at net.minecraft.world.chunk.storage.ExtendedBlockStorage.<init>(ExtendedBlockStorage.java:21) ~[axx.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.readChunkFromNBT(AnvilChunkLoader.java:447) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:128) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92) ~[aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:69) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.redirect$onProvideChunkHead$zmh000(ChunkProviderServer.java:674) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135) ~[on.class:?]
        at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3589) ~[MinecraftServer.class:?]
        at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:820) ~[WorldManager.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:762) ~[WorldManager.class:1.12.2-2705-7.1.0-BETA-3361]
        at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:3541) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.chunk.BlockStateContainer
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        ... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        ... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$onGetStorageSize$FixVanillaBug$zme000(Lnet/minecraft/util/BitArray;)I in mixins.common.core.json:world.chunk.MixinBlockStateContainer failed injection check, (0/1) succeeded. Using refmap mixins.common.refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:938) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:322) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        ... 17 more
```

The method above nor the link above works with sponge 1.12.2-2705-7.1.0-BETA-3361

**Comment by MarkTwoFive** [comment]
@sfxworks You can try the work-around I mentioned in the linked issue.

**Comment by ghost** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2480

Still crashes even with you saying use the link above

I can't run my server or release my pack till you fix this ASAP

**Comment by MarkTwoFive** [comment]
@TacticalUniverse did you try applying the work-around I mentioned?

**Comment by DarkShyMW** [comment]
I have same problem, but i dont have spongeforge..

https://www.toptal.com/developers/hastebin/yesujekewi
