### ISSUE TITLE
Bug with using underline or strikethrough

### ISSUE THREAD

**Issue by Zidane** [Ordinastie/MalisisCore#42]
java.lang.IllegalStateException: Already tesselating!
    at net.minecraft.client.renderer.Tessellator.startDrawing(Tessellator.java:257)
    at net.minecraft.client.renderer.Tessellator.startDrawingQuads(Tessellator.java:247)
    at net.minecraft.client.gui.FontRenderer.renderStringAtPos(FontRenderer.java:494)
    at net.minecraft.client.gui.FontRenderer.renderString(FontRenderer.java:556)
    at net.minecraft.client.gui.FontRenderer.drawString(FontRenderer.java:317)
    at net.malisis.core.client.gui.GuiRenderer.drawText(GuiRenderer.java:508)
    at net.malisis.core.client.gui.GuiRenderer.drawText(GuiRenderer.java:471)
    at net.malisis.core.client.gui.component.interaction.UITextField.drawText(UITextField.java:723)
    at net.malisis.core.client.gui.component.interaction.UITextField.drawForeground(UITextField.java:695)
    at net.malisis.core.client.gui.component.UIComponent.draw(UIComponent.java:889)
    at net.malisis.core.client.gui.component.container.UIContainer.drawForeground(UIContainer.java:524)
    at net.malisis.core.client.gui.component.UIComponent.draw(UIComponent.java:889)
    at net.malisis.core.client.gui.component.container.UIContainer.drawForeground(UIContainer.java:524)
    at net.malisis.core.client.gui.component.UIComponent.draw(UIComponent.java:889)
    at net.malisis.core.client.gui.component.container.UIContainer.drawForeground(UIContainer.java:524)
    at net.malisis.core.client.gui.component.UIComponent.draw(UIComponent.java:889)
    at net.malisis.core.client.gui.GuiRenderer.drawScreen(GuiRenderer.java:229)
    at net.malisis.core.client.gui.MalisisGui.drawScreen(MalisisGui.java:356)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1137)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1057)
    at net.minecraft.client.Minecraft.run(Minecraft.java:951)
    at net.minecraft.client.main.Main.main(Main.java:164)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:85)
    at GradleStart.main(GradleStart.java:45)

I'm getting this whenever I try and apply a color code + underline or strikethrough formatting codes on text in UITextField.

**Comment by Ordinastie** [comment]
Fixed
