### ISSUE TITLE
[1.8.9] Class Cast when hovering over a scroll bar in UITextField

### ISSUE THREAD

**Issue by Zidane** [Ordinastie/MalisisCore#73]
```
[22:51:10] [Client thread/ERROR] [malisiscore]: An error occured while processing event : HoveredStateChange
java.lang.ClassCastException: net.malisis.core.client.gui.component.interaction.UITextField cannot be cast to net.malisis.core.client.gui.component.control.UIScrollBar
    at net.malisis.core.client.gui.component.control.UISlimScrollbar.onMouseOver(UISlimScrollbar.java:175) ~[malisiscore-1.8.9-2.1.7-SNAPSHOT.jar:1.8.9-2.1.7-SNAPSHOT]
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
    at net.malisis.core.client.gui.component.UIComponent.fireEvent(UIComponent.java:665) [UIComponent.class:1.8.9-2.1.7-SNAPSHOT]
    at net.malisis.core.client.gui.component.UIComponent.setHovered(UIComponent.java:399) [UIComponent.class:1.8.9-2.1.7-SNAPSHOT]
    at net.malisis.core.client.gui.MalisisGui.setHoveredComponent(MalisisGui.java:803) [MalisisGui.class:1.8.9-2.1.7-SNAPSHOT]
    at net.malisis.core.client.gui.component.UIComponent.setHovered(UIComponent.java:394) [UIComponent.class:1.8.9-2.1.7-SNAPSHOT]
    at net.malisis.core.client.gui.MalisisGui.handleMouseInput(MalisisGui.java:351) [MalisisGui.class:1.8.9-2.1.7-SNAPSHOT]
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:599) [GuiScreen.class:?]
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1784) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1100) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:384) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:116) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:26) [start/:?]
```

**Comment by Zidane** [comment]
@Ordinastie 

This occurs on 1.9 and 1.9.4.

**Comment by Ordinastie** [comment]
I could not reproduce.
