### ISSUE TITLE
[1.10.2] Crash when used with Schematica

### ISSUE THREAD

**Issue by rigerc** [Ordinastie/MalisisCore#76]
When I load a schematic using the Schematica mod Minecraft crashes. It stops crashing when I disable Malisis. Don't know if anyone can be done about this but thought I'd let you know.

```
[13:09:16] [Client thread/INFO] [STDOUT/]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.41-beta.jar)
  LoadingPlugin (Quark-beta-48.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.0.3.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.0.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 7/26/16 1:09 PM
Description: Unexpected error

java.lang.ClassCastException: com.github.lunatrius.schematica.client.world.chunk.ChunkProviderSchematic cannot be cast to net.minecraft.client.multiplayer.ChunkProviderClient
    at net.minecraft.client.multiplayer.WorldClient.func_72863_F(WorldClient.java:507)
    at net.minecraft.client.multiplayer.WorldClient.func_72863_F(WorldClient.java:49)
    at net.malisis.core.util.chunkblock.ChunkBlockHandler.getAffectedChunks(ChunkBlockHandler.java:338)
    at net.malisis.core.util.chunkcollision.ChunkCollision.getRayTraceResult(ChunkCollision.java:132)
    at net.minecraft.world.World.func_147447_a(World.java:901)
    at com.github.lunatrius.schematica.handler.client.RenderTickHandler.rayTrace(RenderTickHandler.java:50)
    at com.github.lunatrius.schematica.handler.client.RenderTickHandler.onRenderTick(RenderTickHandler.java:23)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_557_RenderTickHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:350)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1074)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72863_F(WorldClient.java:507)
    at net.minecraft.client.multiplayer.WorldClient.func_72863_F(WorldClient.java:49)
    at net.malisis.core.util.chunkblock.ChunkBlockHandler.getAffectedChunks(ChunkBlockHandler.java:338)
    at net.malisis.core.util.chunkcollision.ChunkCollision.getRayTraceResult(ChunkCollision.java:132)
    at net.minecraft.world.World.func_147447_a(World.java:901)
    at com.github.lunatrius.schematica.handler.client.RenderTickHandler.rayTrace(RenderTickHandler.java:50)
    at com.github.lunatrius.schematica.handler.client.RenderTickHandler.onRenderTick(RenderTickHandler.java:23)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_557_RenderTickHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['bsgb'/25, l='MpServer', x=133.25, y=4.00, z=173.38]]
    Chunk stats: MultiplayerChunkCache: 4117, 4117
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (130,4,176), Chunk: (at 2,0,0 in 8,11; contains blocks 128,0,176 to 143,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 4037 game time, 4037 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 8 total; [EntityHorse['Horse'/17, l='MpServer', x=135.13, y=4.00, z=189.98], EntityPig['Pig'/18, l='MpServer', x=142.27, y=4.00, z=207.59], EntityHorse['Horse'/21, l='MpServer', x=189.15, y=4.00, z=240.15], EntityPig['Pig'/23, l='MpServer', x=206.50, y=4.00, z=198.50], EntityPig['Pig'/10, l='MpServer', x=59.50, y=4.00, z=250.50], EntitySheep['Sheep'/12, l='MpServer', x=88.77, y=4.00, z=189.17], EntityCow['Cow'/14, l='MpServer', x=100.50, y=4.00, z=198.50], EntityPlayerSP['bsgb'/25, l='MpServer', x=133.25, y=4.00, z=173.38]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by Ordinastie** [comment]
I don't think this one is on me.
See with @Lunatrius.

**Comment by Lunatrius** [comment]
This was a weird vanilla code issue that I've mistaken as an incompatibility with MalisisCore (https://github.com/Lunatrius/Schematica/issues/168). The issue was resolved on Schematica's side after going over the entire stack trace again.
